# 適用したくないチェック項目を記述
disabled_rules:
  - line_length
  - trailing_whitespace
  - variable_name
  
# Lint対象のファイルのあるパスを記述
included: 
  - BitTrader

# Lint対象から外すファイルのあるパスを記述
excluded: 
  - Pods
  
# パラメータ
# warningを出す値でerrorは出なくなる
line_length: 360

type_body_length:
  - 400 # warning
  - 500 # error